routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PostController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\BookingsController;
use App\Http\Controllers\LoginController;
use App\Models\Categories;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $categories = Categories::getCategories();
    $minimumDate = date('Y-m-d', strtotime("+2 day"));
    return view('home', compact('categories','minimumDate'));
});
Route::post('submit', [BookingsController::class, 'submit'])->name('submit');
Route::post('process', [BookingsController::class, 'process'])->name('process');

Route::get('/login', [LoginController::class, 'login'])->name('login');
Route::post('actionlogin', [LoginController::class, 'actionlogin'])->name('actionlogin');

Route::resource('posts', PostController::class)->middleware('auth');
Route::resource('users', UsersController::class)->middleware('auth');
Route::resource('categories', CategoriesController::class)->middleware('auth');
Route::resource('bookings', BookingsController::class)->middleware('auth');

Route::get('actionlogout', [LoginController::class, 'actionlogout'])->name('actionlogout')->middleware('auth');

app/Models/Bookings.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Bookings extends Model
{
    use HasFactory;

    protected $fillable = [
        'name_customer',
        'phone_customer',
        'service_date'
    ];
}

app/Http/Controllers/BookingsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Categories;
use App\Models\Bookings;
use App\Models\BookingsDetail;

class BookingsController extends Controller
{
    public function index()
    {
        $bookings = Bookings::latest()->paginate(5);
        return view('bookings.index',compact('bookings'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    public function create()
    {
        $categories = Categories::getCategories();
        $minimumDate = date('Y-m-d', strtotime("+2 day"));
        return view('bookings.create',compact('categories','minimumDate'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'name_customer' => 'required',
            'phone_customer' => 'required',
            'service_date' => 'required',
        ]);

        $booking = Bookings::create($request->all());
        $bookingId = $booking['id'];

        $servicesDetails = $request['services'];
        if(!empty($servicesDetails)){
            for($a = 0; $a < count($servicesDetails); $a++){
                if(!empty($servicesDetails[$a])){
                    $value = $servicesDetails[$a];

                    $insert['bookings_id'] = $bookingId;
                    $insert['categories_detail_id'] = $value;
                    BookingsDetail::create($insert);
                }
            }
        }

        return redirect()->route('bookings.index')
                        ->with('success','Category created successfully.');
    }

    public function show(Bookings $booking)
    {
        $bookingId = $booking['id'];
        $servicesDetails = BookingsDetail::getServicesSelected($bookingId);
        return view('bookings.show',compact('booking','servicesDetails'));
    }

    public function edit(Bookings $booking)
    {
        $bookingId = $booking['id'];
        $categories = Categories::getCategories();
        $selectedCategories = BookingsDetail::getServicesSelectedPluck($bookingId);
        $minimumDate = date('Y-m-d', strtotime("+2 day"));
        return view('bookings.edit',compact('booking','categories','selectedCategories','minimumDate'));
    }

    public function update(Request $request, Bookings $booking)
    {
        $request->validate([
            'name_customer' => 'required',
            'phone_customer' => 'required',
            'service_date' => 'required',
        ]);

        $booking->update($request->all());
        $bookingId = $booking['id'];

        // delete
        BookingsDetail::where('bookings_id',$bookingId)->delete();

        // insert
        $servicesDetails = $request['services'];
        if(!empty($servicesDetails)){
            for($a = 0; $a < count($servicesDetails); $a++){
                if(!empty($servicesDetails[$a])){
                    $value = $servicesDetails[$a];

                    $insert['bookings_id'] = $bookingId;
                    $insert['categories_detail_id'] = $value;
                    BookingsDetail::create($insert);
                }
            }
        }

        return redirect()->route('bookings.index')
                        ->with('success','Booking updated successfully');
    }

    public function destroy(Bookings $booking)
    {
        $booking->delete();
        BookingsDetail::where('bookings_id',$booking['id'])->delete();

        return redirect()->route('bookings.index')
                        ->with('success','Booking deleted successfully');
    }

    public function process(Request $request)
    {
        $update['is_processing'] = 'yes';
        Bookings::where('id',$request['booking_id'])->update($update);

        return redirect()->route('bookings.index')
                        ->with('success','Booking process successfully');
    }

    public function submit(Request $request)
    {
        $save['name_customer'] = $request['name_customer'];
        $save['phone_customer'] = $request['phone_customer'];
        $save['service_date'] = $request['service_date'];
        $save['created_at'] = date('Y-m-d H:i:s');
        $booking = Bookings::create($save);
        $bookingId = $booking['id'];

        $servicesDetails = $request['services'];
        if(!empty($servicesDetails)){
            for($a = 0; $a < count($servicesDetails); $a++){
                if(!empty($servicesDetails[$a])){
                    $value = $servicesDetails[$a];

                    $insert['bookings_id'] = $bookingId;
                    $insert['categories_detail_id'] = $value;
                    BookingsDetail::create($insert);
                }
            }
        }

        return response()->json([
            'success' => true
        ], 200);

    }
}

resources/views/bookings/create.blade.php
@extends('template')

@section('content')
<div class="row mt-5 mb-5">
    <div class="col-lg-12 margin-tb">
        <div class="float-left">
            <h2>Create New Booking</h2>
        </div>
        <div class="float-right">
            <a class="btn btn-secondary" href="{{ route('bookings.index') }}"> Back</a>
        </div>
    </div>
</div>

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<form action="{{ route('bookings.store') }}" method="POST">
    @csrf

     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name Customer:</strong>
                <input type="text" name="name_customer" class="form-control" placeholder="Name Customer">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Phone Customer:</strong>
                <input type="number" name="phone_customer" class="form-control" placeholder="Phone Customer">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Service Date:</strong>
                <input type="date" name="service_date" class="form-control" min='{{$minimumDate}}'>
            </div>
        </div>

        @if(count($categories)!=0)
            @foreach($categories as $category)
                <div class="col-xs-4 col-sm-4 col-md-4">
                    <div class="form-group">
                        <strong>{{$category->name_category}}:</strong>
                        @if(count($category->detail)!=0)
                            @foreach($category->detail as $detail)
                                <div class="form-check">
                                  <input class="form-check-input" name="services[]" type="checkbox" value="{{$detail->id}}" id="flexCheckDefault{{$detail->id}}">
                                  <label class="form-check-label" for="flexCheckDefault{{$detail->id}}">
                                    {{$detail->name_category_detail}}
                                  </label>
                                </div>
                            @endforeach
                        @endif
                    </div>
                </div>
            @endforeach
        @endif

        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
</form>
@endsection

resources/views/bookings/edit.blade.php
@extends('template')

@section('content')
    <div class="row mt-5 mb-5">
        <div class="col-lg-12 margin-tb">
            <div class="float-left">
                <h2>Edit Booking</h2>
            </div>
            <div class="float-right">
                <a class="btn btn-secondary" href="{{ route('bookings.index') }}"> Back</a>
            </div>
        </div>
    </div>
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('bookings.update',$booking->id) }}" method="POST">
        @csrf
        @method('PUT')

         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name Customer:</strong>
                    <input type="text" name="name_customer" class="form-control" placeholder="Name Customer" value="{{$booking->name_customer}}">
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Phone Customer:</strong>
                    <input type="number" name="phone_customer" class="form-control" placeholder="Phone Customer" value="{{$booking->phone_customer}}">
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Service Date:</strong>
                    <input type="date" name="service_date" class="form-control" value="{{date('Y-m-d', strtotime($booking->service_date))}}" min='{{$minimumDate}}'>
                </div>
            </div>

            @if(count($categories)!=0)
                @foreach($categories as $category)
                    <div class="col-xs-4 col-sm-4 col-md-4">
                        <div class="form-group">
                            <strong>{{$category->name_category}}:</strong>
                            @if(count($category->detail)!=0)
                                @foreach($category->detail as $detail)
                                    <div class="form-check">
                                      <input class="form-check-input" name="services[]" type="checkbox" value="{{$detail->id}}" id="flexCheckDefault{{$detail->id}}" {{ in_array($detail->id, $selectedCategories) ? ' checked' : '' }}>
                                      <label class="form-check-label" for="flexCheckDefault{{$detail->id}}">
                                        {{$detail->name_category_detail}}
                                      </label>
                                    </div>
                                @endforeach
                            @endif
                        </div>
                    </div>
                @endforeach
            @endif

            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Update</button>
            </div>
        </div>

    </form>
@endsection

resources/views/bookings/index.blade.php
@extends('template')

@section('content')
    <div class="row mt-5 mb-5">
        <div class="col-lg-12 margin-tb">
            <div class="float-left">
                <a class="btn btn-success" href="{{ route('bookings.create') }}"> Create Booking</a>
            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
    <div class="alert alert-success">
        <p>{{ $message }}</p>
    </div>
    @endif

    <table class="table table-bordered">
        <tr>
            <th width="20px" class="text-center">No</th>
            <th>Name Customer</th>
            <th>Phone Customer</th>
            <th>Service Date</th>
            <th>Created</th>
            <th>Process</th>
            <th width="280px"class="text-center">Action</th>
        </tr>
        @foreach ($bookings as $booking)
        <tr>
            <td class="text-center">{{ ++$i }}</td>
            <td>{{ $booking->name_customer }}</td>
            <td>{{ $booking->phone_customer }}</td>
            <td>{{ date('Y-m-d', strtotime($booking->service_date)) }}</td>
            <td>{{ $booking->created_at }}</td>
            <td>
                <form action="{{ route('process') }}" method="POST">
                    @csrf
                    @if($booking->is_processing != 'yes')
                        <input type="hidden" name="booking_id" value="{{$booking->id}}">
                        <button type="submit" class="btn btn-warning btn-sm">Process</button>
                    @endif
                </form>
            </td>
            <td class="text-center">
                <form action="{{ route('bookings.destroy',$booking->id) }}" method="POST">
                    <a class="btn btn-info btn-sm" href="{{ route('bookings.show',$booking->id) }}">Show</a>
                    <a class="btn btn-primary btn-sm" href="{{ route('bookings.edit',$booking->id) }}">Edit</a>
                    @csrf
                    @method('DELETE')
                    @if(!$booking->is_processing)
                        <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Apakah Anda yakin ingin menghapus data ini?')">Delete</button>
                    @endif
                </form>
            </td>
        </tr>
        @endforeach
    </table>

    {!! $bookings->links() !!}

@endsection

resources/views/bookings/show.blade.php
@extends('template')

@section('content')
    <div class="row mt-5 mb-5">
        <div class="col-lg-12 margin-tb">
            <div class="float-left">
                <h2> Show Category</h2>
            </div>
            <div class="float-right">
                <a class="btn btn-secondary" href="{{ route('bookings.index') }}"> Back</a>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name Customer:</strong>
                {{ $booking->name_customer }}
            </div>

            <div class="form-group">
                <strong>Phone Customer:</strong>
                {{ $booking->phone_customer }}
            </div>

            <div class="form-group">
                <strong>Service Date:</strong>
                {{ date('Y-m-d', strtotime($booking->service_date)) }}
            </div>

            <div class="form-group">
                <strong>Created:</strong>
                {{ $booking->created_at }}
            </div>

            <div class="form-group">
                <strong>Services:</strong>
                <br>
                @if(count($servicesDetails)!=0)
                    @foreach($servicesDetails as $detail)
                        - {{ $detail->name_category_detail }} <br>
                    @endforeach
                @endif
            </div>
        </div>
    </div>
@endsection